### PR TITLE
Always close the wallet the same way, and safely

### LINKED ISSUE #1398: RPC wallet segfault on closing wallet
**Describe the bug**
When using the RPC wallet, closing the current wallet (either by `close_wallet`, `create_wallet`, `restore_deterministic_wallet`, or `generate_from_keys`) can sometimes cause a segmentation fault. The `open_wallet` command does not have this bug.

**To Reproduce**
1. Create a wallet (e.g. `create_wallet` with params `{"filename":"foo","password":"foo","password":"English"}`)
2. Close the wallet (any of the above commands can be used, but the simplest is just `close_wallet`)
3. If that succeeded and the RPC wallet didn't crash, then re-open the wallet (`open_wallet` with `{"filename":"foo","password":"foo"}`)
4. Go to (2)

**Expected behaviour**
It should be possible to open and close wallets indefinitely

**Current Behaviour**
At some point (usually within the first couple of attempts) the RPC wallet application will hit a segfault and crash.

**Additional Information (please complete the following information):**
 - Operating System: CentOS 7 container inside Openshift cluster
-  Local node
 - Version of Loki daemon, or most recent commit hash: v8.1.4 (8e3ed0efa8ebbd27890d2d911116282d4f98bcac)

**Solution**
I have identified the cause of the crash and will submit a PR shortly. It is caused by the long-poll thread accessing the no-longer-existing wallet object after the wallet is closed.

### PR DESCRIPTION
**Pull request by lxop**
This especially includes stopping the long-poll
loop thread, which otherwise causes a segfault.

Fixes #1398

### CODE REVIEW

File: src/wallet/wallet_rpc_server.cpp [hunk 1]
```diff
@@ -581,6 +584,24 @@ namespace tools
...
+      stop_long_poll_thread();
+      if (save_current)
+      {
+        LOG_PRINT_L0(tools::wallet_rpc_server::tr("Saving wallet..."));
+        m_wallet->store();
+        LOG_PRINT_L0(tools::wallet_rpc_server::tr("Successfully saved"));
+      }
+      m_wallet->deinit();
+      m_wallet.reset();
+      LOG_PRINT_L0(tools::wallet_rpc_server::tr("Successfully closed"));
```
Comment (jagerman) [inline src/wallet/wallet_rpc_server.cpp:601]: These `L0`s look like leftover noisy debug; they probably belong as `MINFO`s at most.

**Comment by jagerman** [comment]
Aside from the debugging level this looks good to me.

**Review by jagerman — APPROVED** [review]

File: src/wallet/wallet_rpc_server.cpp (hunk 1 above)
Comment (lxop) [reply src/wallet/wallet_rpc_server.cpp:601]: Sure, can do, I just kept them from the original implementation around line 3514. I'll drop them
